site: Otoe County Mutual Aid Association

url: 
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  news:
    output: true
    permalink: /news/:slug
  departments:
    output: true
    permalink: /departments/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "news"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "departments"
    values:
      layout: "department"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/news/page:num/"
  
